// IGO Pharmacy — central product catalog (single source of truth for shop, search & trending)
// Generated from the shop pages. Edit here to add/change products.
window.IGO_PRODUCTS = [
 {
  "id": "wheat-seeds-hd3086",
  "name": "Chemica Wheat Seeds (HD-3086 Improved)",
  "price": 320.0,
  "mrp": 420.0,
  "img": "img/products/wheat-seeds-hd3086.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 24,
  "hot": false
 },
 {
  "id": "paddy-seeds-hybrid",
  "name": "Chemica Paddy Seeds (Hybrid Short Duration)",
  "price": 580.0,
  "mrp": 720.0,
  "img": "img/products/paddy-seeds-hybrid.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 19,
  "hot": false
 },
 {
  "id": "maize-seeds-hybrid",
  "name": "Chemica Maize / Corn Seeds (Single Cross Hybrid)",
  "price": 450.0,
  "mrp": 600.0,
  "img": "img/products/maize-seeds-hybrid.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 25,
  "hot": true
 },
 {
  "id": "groundnut-seeds",
  "name": "Chemica Groundnut Seeds (Bold Spanish)",
  "price": 380.0,
  "mrp": 499.0,
  "img": "img/products/groundnut-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 24,
  "hot": false
 },
 {
  "id": "watermelon-seeds",
  "name": "Chemica Watermelon Seeds (F1 Hybrid Seedless)",
  "price": 1200.0,
  "mrp": 1599.0,
  "img": "img/products/watermelon-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 25,
  "hot": true
 },
 {
  "id": "pumpkin-seeds",
  "name": "Chemica Pumpkin Seeds",
  "price": 200.0,
  "mrp": 250.0,
  "img": "img/products/pumpkin-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 20,
  "hot": false
 },
 {
  "id": "jasmine-seeds",
  "name": "Chemica Jasmine Seeds",
  "price": 150.0,
  "mrp": 200.0,
  "img": "img/products/jasmine-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 25,
  "hot": true
 },
 {
  "id": "cucumber-seeds",
  "name": "Chemica Cucumber Seeds",
  "price": 180.0,
  "mrp": 220.0,
  "img": "img/products/cucumber-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 18,
  "hot": false
 },
 {
  "id": "ladiesfinger-seeds",
  "name": "Chemica Ladiesfinger Seeds",
  "price": 160.0,
  "mrp": 200.0,
  "img": "img/products/ladiesfinger-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 20,
  "hot": false
 },
 {
  "id": "bitter-guard-seeds",
  "name": "Chemica Bitter Guard Seeds",
  "price": 150.0,
  "mrp": 200.0,
  "img": "img/products/bitter-guard-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 25,
  "hot": true
 },
 {
  "id": "sunflower-seeds",
  "name": "Chemica Sunflower Seeds",
  "price": 100.0,
  "mrp": 130.0,
  "img": "img/products/sunflower-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 23,
  "hot": false
 },
 {
  "id": "pomegranate-seeds",
  "name": "Chemica Pomegranate Seeds",
  "price": 600.0,
  "mrp": 750.0,
  "img": "img/products/pomegranate-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 20,
  "hot": false
 },
 {
  "id": "brinjal-seeds",
  "name": "Chemica Brinjal Seeds",
  "price": 120.0,
  "mrp": 150.0,
  "img": "img/products/brinjal-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 20,
  "hot": false
 },
 {
  "id": "muskmelon-seeds",
  "name": "Chemica MuskMelon Seeds",
  "price": 300.0,
  "mrp": 400.0,
  "img": "img/products/muskmelon-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 25,
  "hot": true
 },
 {
  "id": "dianthus-seeds",
  "name": "Chemica Dianthus Seeds",
  "price": 90.0,
  "mrp": 120.0,
  "img": "img/products/dianthus-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 25,
  "hot": true
 },
 {
  "id": "grapes-seeds",
  "name": "Chemica Grapes Seeds",
  "price": 500.0,
  "mrp": 600.0,
  "img": "img/products/grapes-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 17,
  "hot": false
 },
 {
  "id": "calendula-seeds",
  "name": "Chemica Calendula Seeds",
  "price": 80.0,
  "mrp": 100.0,
  "img": "img/products/calendula-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 20,
  "hot": false
 },
 {
  "id": "guava-seeds",
  "name": "Chemica Guava Seeds",
  "price": 400.0,
  "mrp": 500.0,
  "img": "img/products/guava-seeds.webp",
  "cat": "seeds",
  "catLabel": "Seeds",
  "mode": "cart",
  "pack": null,
  "off": 20,
  "hot": false
 },
 {
  "id": "urea-45kg",
  "name": "Chemica Urea 45kg (Neem Coated)",
  "price": 267.0,
  "mrp": null,
  "img": "img/products/urea-45kg.webp",
  "cat": "fertilizers",
  "catLabel": "Fertilizers",
  "mode": "cart",
  "pack": "45kg",
  "off": 0,
  "hot": false
 },
 {
  "id": "dap-50kg",
  "name": "Chemica DAP 50kg (Di-Ammonium Phosphate)",
  "price": 1350.0,
  "mrp": 1500.0,
  "img": "img/products/dap-50kg.webp",
  "cat": "fertilizers",
  "catLabel": "Fertilizers",
  "mode": "cart",
  "pack": "50kg",
  "off": 10,
  "hot": false
 },
 {
  "id": "cow-dung-compost-10kg",
  "name": "Chemica Cow Dung Compost (Dried) 10kg",
  "price": 150.0,
  "mrp": 199.0,
  "img": "img/products/cow-dung-compost-10kg.webp",
  "cat": "fertilizers",
  "catLabel": "Fertilizers",
  "mode": "cart",
  "pack": "10kg",
  "off": 25,
  "hot": false
 },
 {
  "id": "coco-peat-block-5kg",
  "name": "Chemica Coco Peat Block 5kg",
  "price": 180.0,
  "mrp": 249.0,
  "img": "img/products/coco-peat-block-5kg.webp",
  "cat": "fertilizers",
  "catLabel": "Fertilizers",
  "mode": "cart",
  "pack": "5kg",
  "off": 28,
  "hot": true
 },
 {
  "id": "bio-compost-enriched",
  "name": "Chemica Bio Compost (Enriched)",
  "price": 299.0,
  "mrp": 399.0,
  "img": "img/products/bio-compost-enriched.webp",
  "cat": "fertilizers",
  "catLabel": "Fertilizers",
  "mode": "cart",
  "pack": null,
  "off": 25,
  "hot": false
 },
 {
  "id": "ammonium-sulphate",
  "name": "Chemica Ammonium Sulphate (21% N + 24% S)",
  "price": 420.0,
  "mrp": 560.0,
  "img": "img/products/ammonium-sulphate.webp",
  "cat": "fertilizers",
  "catLabel": "Fertilizers",
  "mode": "cart",
  "pack": null,
  "off": 25,
  "hot": false
 },
 {
  "id": "ammonium-nitrate",
  "name": "Chemica Ammonium Nitrate (34% N)",
  "price": 580.0,
  "mrp": 750.0,
  "img": "img/products/ammonium-nitrate.webp",
  "cat": "fertilizers",
  "catLabel": "Fertilizers",
  "mode": "cart",
  "pack": null,
  "off": 23,
  "hot": false
 },
 {
  "id": "kitchen-waste-compost-5kg",
  "name": "Chemica Kitchen Waste Compost 5kg",
  "price": 199.0,
  "mrp": 269.0,
  "img": "img/products/kitchen-waste-compost-5kg.webp",
  "cat": "fertilizers",
  "catLabel": "Fertilizers",
  "mode": "cart",
  "pack": "5kg",
  "off": 26,
  "hot": true
 },
 {
  "id": "can-fertilizer",
  "name": "Chemica CAN (Calcium Ammonium Nitrate)",
  "price": 680.0,
  "mrp": 880.0,
  "img": "img/products/can-fertilizer.webp",
  "cat": "fertilizers",
  "catLabel": "Fertilizers",
  "mode": "cart",
  "pack": null,
  "off": 23,
  "hot": false
 },
 {
  "id": "leaf-compost-10kg",
  "name": "Chemica Leaf Compost (Forest Litter) 10kg",
  "price": 249.0,
  "mrp": 329.0,
  "img": "img/products/leaf-compost-10kg.webp",
  "cat": "fertilizers",
  "catLabel": "Fertilizers",
  "mode": "cart",
  "pack": "10kg",
  "off": 24,
  "hot": false
 },
 {
  "id": "sodium-nitrate",
  "name": "Chemica Sodium Nitrate (16% N)",
  "price": 540.0,
  "mrp": 699.0,
  "img": "img/products/sodium-nitrate.webp",
  "cat": "fertilizers",
  "catLabel": "Fertilizers",
  "mode": "cart",
  "pack": null,
  "off": 23,
  "hot": false
 },
 {
  "id": "power-till",
  "name": "IGO Power-Till Cultivator Kit",
  "price": 2300.0,
  "mrp": null,
  "img": "img/category_equipment_tractor_1783401493658.webp",
  "cat": "equipment",
  "catLabel": "Agri Equipment",
  "mode": "cart",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "mist-pro-sprayer",
  "name": "IGO Mist-Pro 16L Battery Sprayer",
  "price": 3299.0,
  "mrp": 3999.0,
  "img": "img/category_equipment_tractor_1783401493658.webp",
  "cat": "equipment",
  "catLabel": "Agri Equipment",
  "mode": "cart",
  "pack": "16L",
  "off": 18,
  "hot": false
 },
 {
  "id": "drip-flow-kit",
  "name": "IGO Drip-Flow Irrigation Kit",
  "price": 1850.0,
  "mrp": null,
  "img": "img/category_equipment_tractor_1783401493658.webp",
  "cat": "equipment",
  "catLabel": "Agri Equipment",
  "mode": "cart",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "fungiclear-pro",
  "name": "IGO FungiClear Pro (500ml)",
  "price": 1050.0,
  "mrp": null,
  "img": "img/category_pesticides_spray_1783401460265.webp",
  "cat": "pesticides",
  "catLabel": "Crop Protection",
  "mode": "cart",
  "pack": "500ml",
  "off": 0,
  "hot": false
 },
 {
  "id": "insectshield-eco",
  "name": "IGO InsectShield Eco (250ml)",
  "price": 450.0,
  "mrp": 550.0,
  "img": "img/category_pesticides_spray_1783401460265.webp",
  "cat": "pesticides",
  "catLabel": "Crop Protection",
  "mode": "cart",
  "pack": "250ml",
  "off": 18,
  "hot": false
 },
 {
  "id": "weedclear-max",
  "name": "IGO WeedClear Max (1L)",
  "price": 680.0,
  "mrp": null,
  "img": "img/category_pesticides_spray_1783401460265.webp",
  "cat": "pesticides",
  "catLabel": "Crop Protection",
  "mode": "cart",
  "pack": "1L",
  "off": 0,
  "hot": false
 },
 {
  "id": "cattle-boost",
  "name": "IGO Cattle Health Booster (1kg)",
  "price": 650.0,
  "mrp": null,
  "img": "img/category_veterinary_cattle_1783401505951.webp",
  "cat": "veterinary",
  "catLabel": "Cattle Supplements",
  "mode": "cart",
  "pack": "1kg",
  "off": 0,
  "hot": false
 },
 {
  "id": "poultry-care",
  "name": "IGO Poultry Care Combo",
  "price": 380.0,
  "mrp": 450.0,
  "img": "img/category_veterinary_cattle_1783401505951.webp",
  "cat": "veterinary",
  "catLabel": "Poultry Medicines",
  "mode": "cart",
  "pack": null,
  "off": 16,
  "hot": false
 },
 {
  "id": "chemica-amino-acid-fertilizer-liquid",
  "name": "Chemica Amino Acid Fertilizer (Liquid)",
  "price": null,
  "mrp": null,
  "img": "img/products/amino-acid-liquid.png",
  "cat": "fertilizers",
  "catLabel": "Liquid Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-calcium-nitrate-liquid",
  "name": "Chemica Calcium Nitrate (Liquid)",
  "price": null,
  "mrp": null,
  "img": "img/products/calcium-nitrate-liquid.png",
  "cat": "fertilizers",
  "catLabel": "Liquid Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-humic-acid-liquid",
  "name": "Chemica Humic Acid (Liquid)",
  "price": null,
  "mrp": null,
  "img": "img/products/humic-acid-liquid.png",
  "cat": "fertilizers",
  "catLabel": "Liquid Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-liquid-copper",
  "name": "Chemica Liquid Copper",
  "price": null,
  "mrp": null,
  "img": "img/products/liquid-copper.png",
  "cat": "fertilizers",
  "catLabel": "Liquid Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-liquid-iron",
  "name": "Chemica Liquid Iron",
  "price": null,
  "mrp": null,
  "img": "img/products/liquid-iron.png",
  "cat": "fertilizers",
  "catLabel": "Liquid Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-liquid-npk-00-00-50",
  "name": "Chemica Liquid NPK 00-00-50",
  "price": null,
  "mrp": null,
  "img": "img/products/liquid-npk-00-00-50.png",
  "cat": "fertilizers",
  "catLabel": "Liquid Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-liquid-npk-20-20-20",
  "name": "Chemica Liquid NPK 20-20-20",
  "price": null,
  "mrp": null,
  "img": "img/products/liquid-npk-20-20-20.png",
  "cat": "fertilizers",
  "catLabel": "Liquid Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-liquid-urea",
  "name": "Chemica Liquid Urea",
  "price": null,
  "mrp": null,
  "img": "img/products/liquid-urea.png",
  "cat": "fertilizers",
  "catLabel": "Liquid Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-liquid-zinc",
  "name": "Chemica Liquid Zinc",
  "price": null,
  "mrp": null,
  "img": "img/products/liquid-zinc.png",
  "cat": "fertilizers",
  "catLabel": "Liquid Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-npk-12-61-00-liquid",
  "name": "Chemica NPK 12-61-00 (Liquid)",
  "price": null,
  "mrp": null,
  "img": "img/products/npk-12-61-00-liquid.png",
  "cat": "fertilizers",
  "catLabel": "Liquid Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-urea-ammonium-nitrate-uan",
  "name": "Chemica Urea Ammonium Nitrate (UAN)",
  "price": null,
  "mrp": null,
  "img": "img/products/uan-liquid.jpeg",
  "cat": "fertilizers",
  "catLabel": "Liquid Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-amino-acid-fertilizer-powder",
  "name": "Chemica Amino Acid Fertilizer (Powder)",
  "price": null,
  "mrp": null,
  "img": "img/products/amino-acid-powder.jpeg",
  "cat": "fertilizers",
  "catLabel": "Powder Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-azospirillum-bio-fertilizer",
  "name": "Chemica Azospirillum (Bio Fertilizer)",
  "price": null,
  "mrp": null,
  "img": "img/products/azospirillum-powder.jpeg",
  "cat": "fertilizers",
  "catLabel": "Powder Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-boron-20-powder",
  "name": "Chemica Boron 20% (Powder)",
  "price": null,
  "mrp": null,
  "img": "img/products/boron-20-percent.jpeg",
  "cat": "fertilizers",
  "catLabel": "Powder Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-calcium-nitrate-powder",
  "name": "Chemica Calcium Nitrate (Powder)",
  "price": null,
  "mrp": null,
  "img": "img/products/calcium-nitrate-powder.jpeg",
  "cat": "fertilizers",
  "catLabel": "Powder Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-copper-sulphate-powder",
  "name": "Chemica Copper Sulphate (Powder)",
  "price": null,
  "mrp": null,
  "img": "img/products/copper-sulphate.jpeg",
  "cat": "fertilizers",
  "catLabel": "Powder Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-dap-powder-form",
  "name": "Chemica DAP (Powder Form)",
  "price": null,
  "mrp": null,
  "img": "img/products/dap-powder.jpeg",
  "cat": "fertilizers",
  "catLabel": "Powder Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-humic-acid-powder",
  "name": "Chemica Humic Acid (Powder)",
  "price": null,
  "mrp": null,
  "img": "img/products/humic-acid-powder.jpeg",
  "cat": "fertilizers",
  "catLabel": "Powder Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-magnesium-sulphate-powder",
  "name": "Chemica Magnesium Sulphate (Powder)",
  "price": null,
  "mrp": null,
  "img": "img/products/magnesium-sulphate.jpeg",
  "cat": "fertilizers",
  "catLabel": "Powder Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-npk-12-61-00-map-powder",
  "name": "Chemica NPK 12-61-00 (MAP, Powder)",
  "price": null,
  "mrp": null,
  "img": "img/products/npk-12-61-00-map.jpeg",
  "cat": "fertilizers",
  "catLabel": "Powder Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-npk-13-00-45-potassium-nitrate",
  "name": "Chemica NPK 13-00-45 (Potassium Nitrate)",
  "price": null,
  "mrp": null,
  "img": "img/products/npk-13-00-45-potassium-nitrate.jpeg",
  "cat": "fertilizers",
  "catLabel": "Powder Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 },
 {
  "id": "chemica-zinc-sulphate-powder",
  "name": "Chemica Zinc Sulphate (Powder)",
  "price": null,
  "mrp": null,
  "img": "img/products/zinc-sulphate.jpeg",
  "cat": "fertilizers",
  "catLabel": "Powder Fertilizer",
  "mode": "enquire",
  "pack": null,
  "off": 0,
  "hot": false
 }
];
window.IGO_CAT_PAGES = {"seeds": "shop-seeds.html", "fertilizers": "shop-fertilizers.html", "pesticides": "shop-pesticides.html", "equipment": "shop-equipment.html", "veterinary": "shop-veterinary.html"};
window.IGO_CAT_LABELS = {seeds:'Seeds',fertilizers:'Fertilizers',pesticides:'Crop Protection',equipment:'Equipment',veterinary:'Veterinary'};
