// IGO Pharmacy — planned Siddha & Ayurveda product catalog (not yet launched; no live pricing).
window.IGO_PRODUCTS = [
 { "id":"triphala-churnam", "name":"Triphala Churnam", "cat":"churnam", "catLabel":"Churnam & Powders", "price":320, "mrp":450, "img":"https://commons.wikimedia.org/wiki/Special:FilePath/Turmeric-powder.jpg?width=400", "brief":"Classical three-fruit powder blend, supports digestive wellness.", "benefits":["Digestive support","Natural detox","Gentle laxative"], "dosage":"1-2 tsp twice daily with warm water", "pack":"100g" },
 { "id":"ashwagandha-powder", "name":"Ashwagandha Powder", "cat":"churnam", "catLabel":"Churnam & Powders", "price":280, "mrp":399, "img":"img/igo-organic-pharmacy-brand.jpg", "brief":"Root powder from Withania somnifera, supports stress relief and vitality.", "benefits":["Stress relief","Energy support","Adaptogenic"], "dosage":"1-2 grams twice daily with warm milk", "pack":"100g" },
 { "id":"amla-powder", "name":"Amla (Nellikai) Powder", "cat":"churnam", "catLabel":"Churnam & Powders", "price":240, "mrp":350, "img":"img/igo-organic-pharmacy-brand.jpg", "brief":"Indian gooseberry powder, rich in Vitamin C for immunity.", "benefits":["Immunity boost","Hair health","Antioxidant"], "dosage":"1 tsp twice daily with honey", "pack":"100g" },
 { "id":"neem-powder", "name":"Neem Powder", "cat":"churnam", "catLabel":"Churnam & Powders", "price":200, "mrp":300, "img":"img/igo-organic-pharmacy-brand.jpg", "brief":"Traditional leaf powder for skin and blood purification.", "benefits":["Blood purifier","Skin health","Antibacterial"], "dosage":"1/2-1 tsp once daily", "pack":"100g" },
 { "id":"turmeric-powder", "name":"Turmeric (Manjal) Powder", "cat":"churnam", "catLabel":"Churnam & Powders", "price":180, "mrp":280, "img":"https://commons.wikimedia.org/wiki/Special:FilePath/Turmeric-powder.jpg?width=400", "brief":"Golden spice with curcumin for inflammation support and wellness.", "benefits":["Anti-inflammatory","Joint support","Antioxidant"], "dosage":"1/2-1 tsp twice daily with warm milk", "pack":"100g" },
 { "id":"brahmi-powder", "name":"Brahmi Powder", "cat":"churnam", "catLabel":"Churnam & Powders", "price":260, "mrp":380, "img":"img/igo-organic-pharmacy-brand.jpg", "brief":"Brain-supporting herb for focus and mental clarity.", "benefits":["Mental clarity","Memory support","Stress relief"], "dosage":"1 tsp once or twice daily", "pack":"100g" },
 { "id":"nannari-kashayam", "name":"Nannari Kashayam", "cat":"kashayam", "catLabel":"Kashayam & Rasayanam", "price":420, "mrp":599, "img":"https://commons.wikimedia.org/wiki/Special:FilePath/Ayurvada_Medicine_from_Medicinal_Plants_YVSREDDY.jpg?width=400", "brief":"Traditional Tamil Nadu decoction from Indian sarsaparilla root.", "benefits":["Cooling","Summer wellness","Blood purifier"], "dosage":"30 ml twice daily before meals", "pack":"200ml" },
 { "id":"chyawanprash", "name":"Chyawanprash", "cat":"kashayam", "catLabel":"Kashayam & Rasayanam", "price":480, "mrp":680, "img":"img/igo-